@startuml SudoTeam_Sudoku_DomainModel

title SudoTeam_Sudoku_DomainModel

!define MAIN LightSeaGreen
skinparam Class {
	BackgroundColor	White
	BorderColor	MAIN
	FontName	Segoe UI
	FontSize	14
    FontStyle bold
    FontColor Black
	HeaderBackgroundColor MAIN
    ArrowColor MAIN
    ArrowFontColor MAIN
    AttributeFontSize 12
}
skinparam roundcorner 5
skinparam stereotypeCBackgroundColor White
skinparam stereotypeEBackgroundColor Red
skinparam stereotypeABackgroundColor Aqua
skinparam classAttributeIconSize 0

Sudoku *--> Player
Sudoku *--> Board

Board *--> "9" Column
Board *--> "9" Row
Board *--> "9" Box

Column *-->"9" Square
Row *-->"9" Square
Box *-->"9" Square

Square o--> Symbol
Square <|-- PlayableSquare
Square <|-- FixedSquare

Player ..> Assignment
Assignment ..> PlayableSquare
Assignment ..> Symbol
Assignment *--> Result

Result <|-- WinnerResult
Result <|-- InvalidResult
Result ..> Column
Result ..> Row
Result ..> Box

Symbol <|-- NullSymbol
Symbol <|-- OneToNineSymbol

@enduml
